#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "openvpn-server"
name = "OpenVPN Server"
description.en = "OpenVPN Server for secure remote access"

version = "2.6.3~ynh1"

maintainers = ["YunoHost contributors"]

[upstream]
license = "GPL-2.0"
website = "https://openvpn.net/"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

disk = "50M"
ldap = "required"
sso = "not_relevant"

[integration.ram]
build = "50M"
runtime = "50M"

[install]
    [install.port]
    type = "string"
    ask.en = "VPN Port"
    default = "1194"

    [install.protocol]
    type = "select"
    choices = ["udp", "tcp"]
    ask.en = "Protocol"
    default = "udp"

    [install.default_route]
    type = "boolean"
    ask.en = "Route all traffic through VPN?"
    default = true

    [install.dns_provider]
    type = "select"
    choices = ["google", "custom"]
    ask.en = "DNS Provider"
    default = "google"

    [install.custom_dns]
    type = "string"
    ask.en = "Custom DNS Servers (comma separated)"
    optional = true
    visible = "dns_provider == 'custom'"

[resources]
    [resources.system_user]

    [resources.permissions]

    [resources.apt]
    packages = "openvpn, openvpn-auth-ldap, easy-rsa"
